name = input("enter your name:")
result = len(name)
f= input("enter the character you want to find:")
result=name.find(f)
print(f"your name has {result} characters")
print(f"your finding position is {result}")